export default {
  /*
   * 登录
   * COMMON
   * CHECK_LOGIN_SUCCESS: 登录成功
   * CHECK_LOGIN_FAILURE: 登录失败
   */
  CHECK_LOGIN_SUCCESS: 'CHECK_LOGIN_SUCCESS',
  CHECK_LOGIN_FAILURE: 'CHECK_LOGIN_FAILURE',

  /*
  * 加载状态
  * COMMON
  * LOADING_START 开始加载
  * LOADING_END 结束加载
  */
  LOADING_START: 'LOADING_START',
  LOADING_END: 'LOADING_END',

  /*
  * HOME
  * 首页
  * HOME_GETDATA_REQUEST: 首页数据请求
  * HOME_GETDATA_SUCCESS：首页数据请求成功
  * HOME_GETDATA_FAILURE：首页数据请求失败
  * */
  HOME_GETDATA_REQUEST: 'HOME_GETDATA_REQUEST',
  HOME_GETDATA_SUCCESS: 'HOME_GETDATA_SUCCESS',
  HOME_GETDATA_FAILURE: 'HOME_GETDATA_FAILURE',

  /*
 * 专题
 * TOPOIC
 * TOPIC_GETDATA_REQUEST: 专题数据请求
 * TOPIC_GETDATA_SUCCESS：专题数据请求成功
 * TOPIC_GETDATA_FAILURE：专题数据请求失败
 * */
  TOPIC_GETDATA_REQUEST: 'TOPIC_GETDATA_REQUEST',
  TOPIC_GETDATA_SUCCESS: 'TOPIC_GETDATA_SUCCESS',
  TOPIC_GETDATA_FAILURE: 'TOPIC_GETDATA_FAILURE',

  /*
  * CATALOG
  * 分类页中初始化tab数据和当前分类数据
  * CATALOG_INITDATA_GETDATA_REQUEST: 数据请求
  * CATALOG_INITDATA_GETDATA_SUCCESS: 请求成功
  * CATALOG_INITDATA_GETDATA_FAILURE: 请求失败
  * */
  CATALOG_INITDATA_GETDATA_REQUEST: 'CATALOG_INITDATA_GETDATA_REQUEST',
  CATALOG_INITDATA_GETDATA_SUCCESS: 'CATALOG_INITDATA_GETDATA_SUCCESS',
  CATALOG_INITDATA_GETDATA_FAILURE: 'CATALOG_INITDATA_GETDATA_FAILURE',

  /*
   * CATALOG
   * 根据分类ID获取当前商品分类信息跟子分类
   * CATALOG_CATALOGMSG_GETDATA_REQUEST: 数据请求
   * CATALOG_CATALOGMSG_GETDATA_SUCCESS: 请求成功
   * CATALOG_CATALOGMSG_GETDATA_FAILURE: 请求失败
   * */
  CATALOG_CATALOGMSG_GETDATA_REQUEST: 'CATALOG_CATALOGMSG_GETDATA_REQUEST',
  CATALOG_CATALOGMSG_GETDATA_SUCCESS: 'CATALOG_CATALOGMSG_GETDATA_SUCCESS',
  CATALOG_CATALOGMSG_GETDATA_FAILURE: 'CATALOG_CATALOGMSG_GETDATA_FAILURE',

  /*
  * CATALOG
  * 修改分类页面的请求分类ID跟当前TabIndex值
  * */
  CATALOG_CHANGEIDANDTABINDEX: 'CATALOG_CHANGEIDANDTABINDEX',

  /*
  * GOODS
  * 在售商品数量
  * GOODS_COUNT_GETDATA_REQUSET: 数据请求
  * GOODS_COUNT_GETDATA_SUCCESS: 请求成功
  * GOODS_COUNT_GETDATA_FAILURE: 请求失败
  * */
  GOODS_COUNT_GETDATA_REQUSET: 'GOODS_COUNT_GETDATA_REQUSET',
  GOODS_COUNT_GETDATA_SUCCESS: 'GOODS_COUNT_GETDATA_SUCCESS',
  GOODS_COUNT_GETDATA_FAILURE: 'GOODS_COUNT_GETDATA_FAILURE',

  /*
  * GOODS
  * 获取商品数据
  * GOODS_LIST_GETDATA_REQUSET: 数据请求
  * GOODS_LIST_GETDATA_SUCCESS: 请求成功
  * GOODS_LIST_GETDATA_FAILURE: 请求失败
  * */
  GOODS_LIST_GETDATA_REQUSET: 'GOODS_LIST_GETDATA_REQUSET',
  GOODS_LIST_GETDATA_SUCCESS: 'GOODS_LIST_GETDATA_SUCCESS',
  GOODS_LIST_GETDATA_FAILURE: 'GOODS_LIST_GETDATA_FAILURE',
}