export default {
  /*
   * 登录
   * COMMON
   * CHECK_LOGIN_SUCCESS: 登录成功
   * CHECK_LOGIN_FAILURE: 登录失败
   */
  CHECK_LOGIN_SUCCESS: 'CHECK_LOGIN_SUCCESS',
  CHECK_LOGIN_FAILURE: 'CHECK_LOGIN_FAILURE',

  /*
  * 加载状态
  * COMMON
  * LOADING_START 开始加载
  * LOADING_END 结束加载
  */
  LOADING_START: 'LOADING_START',
  LOADING_END: 'LOADING_END',

  /*
  * HOME
  * 首页
  * HOME_GETDATA_REQUEST: 首页数据请求
  * HOME_GETDATA_SUCCESS：首页数据请求成功
  * HOME_GETDATA_FAILURE：首页数据请求失败
  * */
  HOME_GETDATA_REQUEST: 'HOME_GETDATA_REQUEST',
  HOME_GETDATA_SUCCESS: 'HOME_GETDATA_SUCCESS',
  HOME_GETDATA_FAILURE: 'HOME_GETDATA_FAILURE',

  /*
 * 专题
 * TOPOIC
 * TOPIC_GETDATA_REQUEST: 专题数据请求
 * TOPIC_GETDATA_SUCCESS：专题数据请求成功
 * TOPIC_GETDATA_FAILURE：专题数据请求失败
 * */
  TOPIC_GETDATA_REQUEST: 'TOPIC_GETDATA_REQUEST',
  TOPIC_GETDATA_SUCCESS: 'TOPIC_GETDATA_SUCCESS',
  TOPIC_GETDATA_FAILURE: 'TOPIC_GETDATA_FAILURE',
}